[0.273s] Invoking command in '/home/vsss/repos/vsss24-ws/src/univector': AMENT_PREFIX_PATH=/home/vsss/repos/vsss24-ws/install/univector:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/vsss/repos/vsss24-ws/build/univector/pytest.xml --junit-prefix=univector -o cache_dir=/home/vsss/repos/vsss24-ws/build/univector/.pytest_cache PYTHONPATH=/home/vsss/repos/vsss24-ws/install/univector/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
[0.572s] [1m============================= test session starts ==============================[0m
[0.572s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.578s] cachedir: /home/vsss/repos/vsss24-ws/build/univector/.pytest_cache
[0.578s] rootdir: /home/vsss/repos/vsss24-ws/src/univector
[0.578s] plugins: ament-flake8-0.12.9, launch-testing-1.0.4, ament-copyright-0.12.9, ament-xmllint-0.12.9, ament-pep257-0.12.9, ament-lint-0.12.9, launch-testing-ros-0.19.6, rerunfailures-12.0, colcon-core-0.12.1, cov-4.1.0, repeat-0.9.1
[0.678s] [1mcollecting ... [0m[1m
[0.678s] collected 0 items / 1 error                                                    [0m
[0.700s] 
[0.700s] ==================================== ERRORS ====================================
[0.700s] [31m[1m________________________ ERROR collecting test session _________________________[0m
[0.701s] [1m[31m/usr/lib/python3/dist-packages/pluggy/hooks.py[0m:286: in __call__
[0.746s]     [94mreturn[39;49;00m [96mself[39;49;00m._hookexec([96mself[39;49;00m, [96mself[39;49;00m.get_hookimpls(), kwargs)
[0.746s] [1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:92: in _hookexec
[0.746s]     [94mreturn[39;49;00m [96mself[39;49;00m._inner_hookexec(hook, methods, kwargs)
[0.747s] [1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:83: in <lambda>
[0.747s]     [96mself[39;49;00m._inner_hookexec = [94mlambda[39;49;00m hook, methods, kwargs: hook.multicall(
[0.747s] [1m[31m/usr/lib/python3/dist-packages/_pytest/python.py[0m:200: in pytest_collect_file
[0.747s]     module: Module = ihook.pytest_pycollect_makemodule(path=path, parent=parent)
[0.747s] [1m[31m/usr/lib/python3/dist-packages/pluggy/hooks.py[0m:286: in __call__
[0.747s]     [94mreturn[39;49;00m [96mself[39;49;00m._hookexec([96mself[39;49;00m, [96mself[39;49;00m.get_hookimpls(), kwargs)
[0.748s] [1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:92: in _hookexec
[0.748s]     [94mreturn[39;49;00m [96mself[39;49;00m._inner_hookexec(hook, methods, kwargs)
[0.748s] [1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:83: in <lambda>
[0.748s]     [96mself[39;49;00m._inner_hookexec = [94mlambda[39;49;00m hook, methods, kwargs: hook.multicall(
[0.748s] [1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py[0m:188: in pytest_pycollect_makemodule
[0.748s]     entrypoint = find_launch_test_entrypoint(path)
[0.748s] [1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py[0m:181: in find_launch_test_entrypoint
[0.748s]     module = path.pyimport()
[0.749s] [1m[31m/usr/lib/python3/dist-packages/py/_path/local.py[0m:704: in pyimport
[0.749s]     [96m__import__[39;49;00m(modname)
[0.749s] [1m[31m/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py[0m:170: in exec_module
[0.749s]     exec(co, module.[91m__dict__[39;49;00m)
[0.749s] [1m[31mtest/test_hyperbolicSpiral.py[0m:1: in <module>
[0.749s]     [94mimport[39;49;00m [04m[96munivector[39;49;00m[04m[96m.[39;49;00m[04m[96munivector[39;49;00m[04m[96m.[39;49;00m[04m[96mun_field[39;49;00m [94mas[39;49;00m [04m[96munivector[39;49;00m
[0.749s] [1m[31mE   ModuleNotFoundError: No module named 'univector.univector'[0m
[0.749s] -- generated xml file: /home/vsss/repos/vsss24-ws/build/univector/pytest.xml ---
[0.749s] =========================== short test summary info ============================
[0.750s] ERROR  - ModuleNotFoundError: No module named 'univector.univector'
[0.750s] !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[0.750s] [31m=============================== [31m[1m1 error[0m[31m in 0.18s[0m[31m ===============================[0m
[0.784s] Invoked command in '/home/vsss/repos/vsss24-ws/src/univector' returned '2': AMENT_PREFIX_PATH=/home/vsss/repos/vsss24-ws/install/univector:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/vsss/repos/vsss24-ws/build/univector/pytest.xml --junit-prefix=univector -o cache_dir=/home/vsss/repos/vsss24-ws/build/univector/.pytest_cache PYTHONPATH=/home/vsss/repos/vsss24-ws/install/univector/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
